/**
 * Comprehensive CBSE & NCERT K-12 Curriculum Catalog
 * Maps each class to its official subjects and each subject to its authentic, updated CBSE/NCERT chapters.
 * Extracted & aligned with official NCERT textbook catalog (https://ncert.nic.in/textbook.php) & NEP/NCF 2024.
 */

export interface ClassCurriculum {
  subjects: {
    [subjectName: string]: string[];
  };
}

export const CBSE_NCERT_CURRICULUM: Record<string, ClassCurriculum> = {
  "Nursery / KG": {
    subjects: {
      "Foundational Literacy & English": [
        "Alphabet & Phonics (A to Z)",
        "Rhymes, Poems & Sing-Alongs",
        "Sight Words & Letter Sounds",
        "Picture Reading & Story Listening",
        "Pattern Tracing & Pre-Writing Strokes",
        "Full Syllabus / Early Learning"
      ],
      "Foundational Numeracy & Math": [
        "Pre-Number Concepts (Big/Small, Tall/Short, Heavy/Light)",
        "Numbers and Counting (1 to 20)",
        "Shapes and Basic Geometry (Circle, Square, Triangle)",
        "Colors Recognition & Sorting",
        "Comparing Quantities (More/Less)",
        "Full Syllabus / Early Numeracy"
      ],
      "General Awareness & EVS": [
        "My Body Parts & Sense Organs",
        "My Family and Home",
        "Fruits, Vegetables & Healthy Food",
        "Animals, Birds & Their Sounds",
        "Seasons & Nature",
        "Good Habits, Cleanliness & Manners",
        "Full Syllabus / Activity Exploration"
      ],
      "Hindi (बालवाटिका / आरंभिक हिंदी)": [
        "अ से ज्ञ वर्णमाला परिचय",
        "बालगीत एवं तुकबंदी",
        "चित्र देखकर शब्द पहचान",
        "गिनती (1 से 10 मौखिक)",
        "रंग, फल और जानवरों के नाम",
        "सम्पूर्ण पाठ्यक्रम"
      ],
    }
  },

  "Class 1": {
    subjects: {
      "Mathematics (Joyful Mathematics)": [
        "Chapter 1: Finding the Furry Cat! (Pre-number Concepts)",
        "Chapter 2: What is Long? What is Round? (Shapes & Space)",
        "Chapter 3: Mango Treat (Numbers 1 to 9)",
        "Chapter 4: Making 10 (Numbers 10 to 20)",
        "Chapter 5: How Many? (Addition & Subtraction up to 20)",
        "Chapter 6: Vegetable Farm (Numbers 21 to 50)",
        "Chapter 7: Lina's Family (Measurement)",
        "Chapter 8: Fun with Numbers (Numbers 51 to 99)",
        "Chapter 9: Utsav (Patterns)",
        "Chapter 10: How do I Spend my Day? (Time)",
        "Chapter 11: How Many Times? (Multiplication Readiness)",
        "Chapter 12: How Much Can We Spend? (Money)",
        "Chapter 13: So Many Toys (Data Handling)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Mridang)": [
        "Unit 1: My Family and Me (Two Little Hands, Greetings)",
        "Unit 2: Life Around Us (Picture Time, The Cap-seller and the Monkeys)",
        "Unit 3: Food and Water (Fun with Words, Chhuk-Chhuk-Chhuk)",
        "Unit 4: Do Animals Grow? (The Little Bird, Mittu and the Yellow Mango)",
        "Unit 5: Bright Sky (Clouds, Anand's Rainbow)",
        "Phonics, Sight Words & Basic Rhymes",
        "Grammar: Naming Words, Action Words & Simple Sentences",
        "Reading Comprehension & Short Stories",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (सारंगी)": [
        "इकाई 1: परिवार (मीना का परिवार, दादा-दादी, रीना का घर)",
        "इकाई 2: रंग ही रंग (वाह! मेरे घोड़े, चार चने, पतंग)",
        "इकाई 3: हमारा खान-पान (आम की टोकरी, रसोई, मीठे बोल)",
        "इकाई 4: प्रकृति (बारिश, बादल, चंदा मामा)",
        "इकाई 5: पशु-पक्षी (चिड़िया, बिल्ली मौसी, तोता)",
        "वर्णमाला, स्वर, व्यंजन एवं मात्रा अभ्यास",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "The World Around Us / EVS": [
        "Theme 1: Myself and My Body",
        "Theme 2: My Family, Friends and Home",
        "Theme 3: Plants and Animals Around Me",
        "Theme 4: Food We Eat and Clean Water",
        "Theme 5: Good Habits, Safety and Hygiene",
        "Theme 6: Seasons, Festivals and Celebrations",
        "Full Syllabus / Activity Exploration"
      ],
    }
  },

  "Class 2": {
    subjects: {
      "Mathematics (Joyful Mathematics)": [
        "Chapter 1: Day at the Beach (Shapes and Spatial Understanding)",
        "Chapter 2: Shapes Around Us (3D Shapes & Tracing)",
        "Chapter 3: Fun with Numbers (Numbers 1 to 100, Place Value)",
        "Chapter 4: Shadow Story (Addition / Together)",
        "Chapter 5: Playing with Lines (Straight and Curved Lines)",
        "Chapter 6: Decoration for Festival (Addition and Subtraction)",
        "Chapter 7: Rani's Gift (Measurement - Length)",
        "Chapter 8: Grouping and Sharing (Multiplication & Division Readiness)",
        "Chapter 9: Which Season is it? (Time and Calendar)",
        "Chapter 10: Fun at the Fair (Money)",
        "Chapter 11: Data Handling (Pictures and Lists)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Mridang)": [
        "Unit 1: My Family and Friends (My Bicycle, Picture Reading)",
        "Unit 2: Sharing and Caring (The Wooden Bowl, The Crow and the Pitcher)",
        "Unit 3: On the Move (The Bus, Going to School)",
        "Unit 4: Life Around Us (Rain in Summer, The Ant and the Dove)",
        "Unit 5: Harmony (The Wind and the Sun)",
        "Grammar: Nouns, Pronouns, Verbs, Adjectives & Prepositions",
        "Creative Writing: Simple Sentences, Picture Composition",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (सारंगी)": [
        "इकाई 1: परिवार (नीमा की दादी, घर, माँ)",
        "इकाई 2: रंग-बिरंगी दुनिया (तितली और कली, आसमान गिरा)",
        "इकाई 3: हमारा परिवेश (मेला, गाँव, हमारा विद्यालय)",
        "इकाई 4: प्रकृति (पानी रे पानी, पेड़, तितली)",
        "इकाई 5: खेल और खिलौने (गेंद का बल्ला, शेर और चूहा)",
        "व्याकरण: संज्ञा, सर्वनाम, विलोम शब्द, वाक्य रचना",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "The World Around Us / EVS": [
        "Chapter 1: Our Environment and Neighborhood",
        "Chapter 2: Plant Kingdom (Trees, Shrubs, Herbs)",
        "Chapter 3: Animal Friends and Their Shelters",
        "Chapter 4: Food for Health and Clean Water",
        "Chapter 5: Our Clothes and Weather",
        "Chapter 6: Safety Rules and First Aid",
        "Chapter 7: Transport and Communication",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 3": {
    subjects: {
      "Mathematics (Maths Mela)": [
        "Chapter 1: What's in a Name? (Numbers & Patterns)",
        "Chapter 2: Toy Joy (Numbers up to 1000)",
        "Chapter 3: Double Century (Counting by Tens, Hundreds)",
        "Chapter 4: Vacation with My Nani (Addition & Subtraction)",
        "Chapter 5: Fun with Shapes (2D & 3D Shapes)",
        "Chapter 6: House of Hundreds – I (Place Value & Addition)",
        "Chapter 7: Raksha Bandhan (Measurement & Patterns)",
        "Chapter 8: Fair Share (Division & Fractions Readiness)",
        "Chapter 9: House of Hundreds – II (Multiplication Concepts)",
        "Chapter 10: Fun at the Class Party (Multiplication)",
        "Chapter 11: Filling and Lifting (Measurement: Capacity & Weight)",
        "Chapter 12: Give and Take (Money & Transactions)",
        "Chapter 13: Time Goes On (Time, Clocks & Calendar)",
        "Chapter 14: The Smart Chart (Data Representation)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Santoor)": [
        "Unit 1: Fun with Friends (Colours, Best Friends)",
        "Unit 2: Toys and Games (The Toy Train, Flying High)",
        "Unit 3: The World of Animals (The Clever Fox, Birds of Feather)",
        "Unit 4: Life in Nature (The Big Tree, The River)",
        "Unit 5: Wonder and Magic (The Star, The Rainbow)",
        "Grammar: Nouns, Pronouns, Verbs, Adjectives, Tenses, Conjunctions",
        "Writing: Paragraph Writing, Diary Entry, Informal Note",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (वीणा)": [
        "इकाई 1: सीख (हम सब सुमन एक उपवन के, बया हमारी चिड़िया रानी)",
        "इकाई 2: प्रकृति और हम (पेड़ों का महत्व, तितली रानी)",
        "इकाई 3: हमारा समाज और संस्कृति (त्योहारों का देश, दादी की सीख)",
        "इकाई 4: बुद्धि और चतुराई (तेनालीराम की चतुराई, बीरबल की खिचड़ी)",
        "इकाई 5: बाल कविताएँ एवं कहानियाँ (जादुई छड़ी, चंदा मामा दूर के)",
        "व्याकरण: संज्ञा, सर्वनाम, विशेषण, क्रिया, विलोम, पर्यायवाची",
        "रचनात्मक लेखन: अनुच्छेद लेखन, चित्र वर्णन",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "The World Around Us (Our Wondrous World)": [
        "Unit 1: Family and Community (My Family, Living and Growing Together)",
        "Unit 2: Food and Nutrition (What We Eat, Food from Plants and Animals)",
        "Unit 3: Shelter and Living Spaces (Our Homes, Animal Shelters)",
        "Unit 4: Water in Our Lives (Sources of Water, Water Conservation)",
        "Unit 5: Travel and Places (Ways to Travel, Exploring Neighborhood)",
        "Unit 6: Things We Make and Do (Pottery, Textiles, Craftwork)",
        "Unit 7: Plants and Animals in Nature (Interdependence, Care for Nature)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Arts (Bansuri - I)": [
        "Visual Arts: Lines, Shapes, Colors and Forms",
        "Folk Arts and Traditional Craftwork",
        "Clay Modeling, Paper Craft and Origami",
        "Music, Rhythm, Songs and Movements",
        "Full Syllabus / Activity Exploration"
      ],
      "Physical Education and Well Being (Khel Yoga)": [
        "Body Postures and Asanas for Children",
        "Breathing Exercises (Pranayama Awareness)",
        "Indigenous Games and Physical Activities",
        "Personal Hygiene, Clean Food and Healthy Habits",
        "Full Syllabus / Wellness"
      ],
    }
  },

  "Class 4": {
    subjects: {
      "Mathematics (Math-Magic / Math-Mela)": [
        "Chapter 1: Building with Bricks",
        "Chapter 2: Long and Short",
        "Chapter 3: A Trip to Bhopal",
        "Chapter 4: Tick-Tick-Tick",
        "Chapter 5: The Way The World Looks",
        "Chapter 6: The Junk Seller",
        "Chapter 7: Jugs and Mugs",
        "Chapter 8: Carts and Wheels",
        "Chapter 9: Halves and Quarters",
        "Chapter 10: Play with Patterns",
        "Chapter 11: Tables and Shares",
        "Chapter 12: How Heavy? How Light?",
        "Chapter 13: Field and Fences",
        "Chapter 14: Smart Charts",
        "Full Syllabus / Mixed Chapters"
      ],
      "Environmental Studies (Looking Around / Our Wondrous World)": [
        "Chapter 1: Going to School",
        "Chapter 2: Ear to Ear",
        "Chapter 3: A Day with Nandu",
        "Chapter 4: The Story of Amrita",
        "Chapter 5: Anita and the Honeybees",
        "Chapter 6: Omana's Journey",
        "Chapter 7: From the Window",
        "Chapter 8: Reaching Grandmother's House",
        "Chapter 9: Changing Families",
        "Chapter 10: Hu Tu Tu, Hu Tu Tu",
        "Chapter 11: The Valley of Flowers",
        "Chapter 12: Changing Times",
        "Chapter 13: A River's Tale",
        "Chapter 14: Basva's Farm",
        "Chapter 15: From Market to Home",
        "Chapter 16: A Busy Month",
        "Chapter 17: Nandita in Mumbai",
        "Chapter 18: Too Much Water, Too Little Water",
        "Chapter 19: Abdul in the Garden",
        "Chapter 20: Eating Together",
        "Chapter 21: Food and Fun",
        "Chapter 22: The World in My Home",
        "Chapter 23: Pochampalli",
        "Chapter 24: Home and Abroad",
        "Chapter 25: Spicy Riddles",
        "Chapter 26: Defence Officer: Wahida",
        "Chapter 27: Chuskit Goes to School",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Marigold)": [
        "Unit 1: Wake Up! & Neha's Alarm Clock",
        "Unit 2: Noses & The Little Fir Tree",
        "Unit 3: Run! & Nasruddin's Aim",
        "Unit 4: Why? & Alice in Wonderland",
        "Unit 5: Don't be Afraid of the Dark & Helen Keller",
        "Unit 6: Hiawatha & The Scholar's Mother Tongue",
        "Unit 7: A Watering Rhyme & The Giving Tree",
        "Unit 8: Books & Going to Buy a Book",
        "Unit 9: The Naughty Boy & Pinocchio",
        "Grammar: Tenses, Prepositions, Conjunctions, Punctuations",
        "Writing: Paragraph Writing, Informal Letter, Story Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (रिमझिम)": [
        "पाठ 1: मन के भोले-भाले बादल",
        "पाठ 2: जैसा सवाल वैसा जवाब",
        "पाठ 3: किरमिच की गेंद",
        "पाठ 4: पापा जब बच्चे थे",
        "पाठ 5: दोस्त की पोशाक",
        "पाठ 6: नाव बनाओ नाव बनाओ",
        "पाठ 7: दान का हिसाब",
        "पाठ 8: कौन?",
        "पाठ 9: स्वतंत्रता की ओर",
        "पाठ 10: थप्प रोटी थप्प दाल",
        "पाठ 11: पढ़क्कू की सूझ",
        "पाठ 12: सुनीता की पहिया कुर्सी",
        "पाठ 13: हुदहुद",
        "पाठ 14: मुफ्त ही मुफ्त",
        "व्याकरण: संज्ञा, सर्वनाम, विशेषण, क्रिया, लिंग, वचन, मुहावरे",
        "सम्पूर्ण पाठ्यक्रम"
      ],
    }
  },

  "Class 5": {
    subjects: {
      "Mathematics (Math-Magic / Math-Mela)": [
        "Chapter 1: The Fish Tale",
        "Chapter 2: Shapes and Angles",
        "Chapter 3: How Many Squares?",
        "Chapter 4: Parts and Wholes",
        "Chapter 5: Does it Look the Same?",
        "Chapter 6: Be My Multiple, I'll be Your Factor",
        "Chapter 7: Can You See the Pattern?",
        "Chapter 8: Mapping Your Way",
        "Chapter 9: Boxes and Sketches",
        "Chapter 10: Tenths and Hundredths",
        "Chapter 11: Area and its Boundary",
        "Chapter 12: Smart Charts",
        "Chapter 13: Ways to Multiply and Divide",
        "Chapter 14: How Big? How Heavy?",
        "Full Syllabus / Mixed Chapters"
      ],
      "Environmental Studies (Looking Around / Our Wondrous World)": [
        "Chapter 1: Super Senses",
        "Chapter 2: A Snake Charmer's Story",
        "Chapter 3: From Tasting to Digesting",
        "Chapter 4: Mangoes Round the Year",
        "Chapter 5: Seeds and Seeds",
        "Chapter 6: Every Drop Counts",
        "Chapter 7: Experiments with Water",
        "Chapter 8: A Treat for Mosquitoes",
        "Chapter 9: Up You Go!",
        "Chapter 10: Walls Tell Stories",
        "Chapter 11: Sunita in Space",
        "Chapter 12: What if it Finishes...?",
        "Chapter 13: A Shelter so High!",
        "Chapter 14: When the Earth Shook!",
        "Chapter 15: Blow Hot, Blow Cold",
        "Chapter 16: Who will do this Work?",
        "Chapter 17: Across the Wall",
        "Chapter 18: No Place for Us?",
        "Chapter 19: A Seed tells a Farmer's Story",
        "Chapter 20: Whose Forests?",
        "Chapter 21: Like Father, Like Daughter",
        "Chapter 22: On the Move Again",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Marigold)": [
        "Unit 1: Ice-cream Man & Wonderful Waste!",
        "Unit 2: Teamwork & Flying Together",
        "Unit 3: My Shadow & Robinson Crusoe Discovers a Footprint",
        "Unit 4: Crying & My Elder Brother",
        "Unit 5: The Lazy Frog & Rip Van Winkle",
        "Unit 6: Class Discussion & The Talkative Barber",
        "Unit 7: Topsy-turvy Land & Gulliver's Travels",
        "Unit 8: Nobody's Friend & The Little Bully",
        "Unit 9: Sing a Song of People & Around the World",
        "Unit 10: Malu Bhalu & Who Will be Ningthou?",
        "Grammar: Tenses, Prepositions, Voice, Modals, Conjunctions",
        "Writing: Essay Writing, Letter Writing, Notice Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (रिमझिम)": [
        "पाठ 1: राख की रस्सी",
        "पाठ 2: फ़सलों के त्योहार",
        "पाठ 3: खिलौनेवाला",
        "पाठ 4: नन्हा फ़नकार",
        "पाठ 5: जहाँ चाह वहाँ राह",
        "पाठ 6: चिट्ठी का सफ़र",
        "पाठ 7: डाकिए की कहानी, कंवरसिंह की जुबानी",
        "पाठ 8: वे दिन भी क्या दिन थे",
        "पाठ 9: एक माँ की बेबसी",
        "पाठ 10: एक दिन की बादशाहत",
        "पाठ 11: चावल की रोटियाँ",
        "पाठ 12: गुरु और चेला",
        "पाठ 13: स्वामी की दादी",
        "पाठ 14: बाघ आया उस रात",
        "पाठ 15: बिशन की दिलेरी",
        "पाठ 16: पानी रे पानी",
        "पाठ 17: छोटी-सी हमारी नदी",
        "पाठ 18: चुनौती हिमालय की",
        "व्याकरण: संज्ञा, सर्वनाम, विशेषण, क्रिया, काल, मुहावरे, अपठित गद्यांश",
        "सम्पूर्ण पाठ्यक्रम"
      ],
    }
  },

  "Class 6": {
    subjects: {
      "Science (Curiosity)": [
        "Chapter 1: The Wonderful World of Science",
        "Chapter 2: Diversity in the Living World",
        "Chapter 3: Mindful Eating: A Path to a Healthy Body",
        "Chapter 4: Exploring Magnets",
        "Chapter 5: Measurement of Length and Motion",
        "Chapter 6: Materials Around Us",
        "Chapter 7: Temperature and its Measurement",
        "Chapter 8: Water in Our Lives",
        "Chapter 9: Methods of Separation in Everyday Life",
        "Chapter 10: Living Creatures: Exploring their Characteristics",
        "Chapter 11: Nature's Treasures",
        "Chapter 12: Beyond Earth",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics (Ganita Prakash)": [
        "Chapter 1: Patterns in Mathematics",
        "Chapter 2: Lines and Angles",
        "Chapter 3: Number Play",
        "Chapter 4: Data Handling and Presentation",
        "Chapter 5: Prime Time",
        "Chapter 6: Perimeter and Area",
        "Chapter 7: Fractions",
        "Chapter 8: Playing with Constructions & Symmetry",
        "Chapter 9: Ratio and Proportion",
        "Chapter 10: Introduction to Algebra",
        "Full Syllabus / Mixed Chapters"
      ],
      "Social Science (Exploring Society: India and Beyond)": [
        "Theme A - Ch 1: Locating Places on the Earth",
        "Theme A - Ch 2: Oceans and Continents",
        "Theme A - Ch 3: Landforms and Life",
        "Theme B - Ch 4: Timeline and Sources of History",
        "Theme B - Ch 5: India, That is Bharat",
        "Theme B - Ch 6: The Beginning of Indian Civilisation",
        "Theme B - Ch 7: India's Cultural Roots",
        "Theme C - Ch 8: Unity in Diversity, or 'Many in the One'",
        "Theme C - Ch 9: Family and Community",
        "Theme C - Ch 10: Grassroots Democracy — Part 1: Rural Areas",
        "Theme C - Ch 11: Grassroots Democracy — Part 2: Urban Areas",
        "Theme C - Ch 12: The Value of Work",
        "Theme C - Ch 13: Economic Activities Around Us",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Poorvi)": [
        "Unit 1: Fables and Folk Tales (A Bottle of Dew, The Raven and the Fox)",
        "Unit 2: Friendship (The Unlikely Best Friends, A Friend's Greeting)",
        "Unit 3: Nurturing Nature (The Cherry Tree, What a Bird Thought)",
        "Unit 4: Sports and Wellness (The Miracle, The Winner)",
        "Unit 5: Culture and Tradition (Hamara Bharat: Incredible India!)",
        "Grammar: Nouns, Pronouns, Verbs, Tenses, Prepositions, Adjectives",
        "Writing: Paragraph Writing, Informal Letter, Notice Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (मल्हार)": [
        "इकाई 1: मातृभूमि (मातृभूमि, बचपन के दिन)",
        "इकाई 2: प्रकृति और पर्यावरण (तरुवर, मेघ आए)",
        "इकाई 3: साहस और प्रेरणा (हार की जीत, हिम्मत करने वालों की)",
        "इकाई 4: कला और संस्कृति (चित्रकार की चतुराई, हमारी विरासत)",
        "इकाई 5: ज्ञान और विज्ञान (समय का सदुपयोग, सोच और खोज)",
        "व्याकरण: संज्ञा, सर्वनाम, विशेषण, क्रिया, काल, कारक, अपठित गद्यांश",
        "रचनात्मक लेखन: पत्र लेखन, संवाद लेखन, निबंध लेखन",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Sanskrit (दीपकम / रुचिरा)": [
        "पाठ 1: वन्दना",
        "पाठ 2: परिचयः",
        "पाठ 3: एषः कः? एषा का?",
        "पाठ 4: क्रीडाक्षेत्रम्",
        "पाठ 5: अस्माकं विद्यालयः",
        "पाठ 6: भारतदेशः",
        "पाठ 7: सुभाषितानि",
        "व्याकरण: शब्दरूपाणि, धातुरूपाणि, कारक-परिचयः",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Arts (Kriti-I)": [
        "Visual Arts: Exploration of Lines, Shapes, Colors & Textures",
        "Folk Art Traditions & Cultural Expressions of India",
        "Clay Modeling, Paper Art & Three-Dimensional Construction",
        "Music, Movement & Theater Basics",
        "Full Syllabus / Creative Expressions"
      ],
      "Vocational Education (Kaushal Bodh)": [
        "Module 1: Life Skills, Handcrafts and Daily Living Arts",
        "Module 2: Basics of Digital Tools and Safe Computing",
        "Module 3: Agriculture, Gardening and Plant Care",
        "Module 4: Community Service and Teamwork",
        "Full Syllabus / Hands-on Vocational"
      ],
      "Physical Education and Well Being (Khel Yatra)": [
        "Unit 1: Fundamental Movement Skills & Coordination",
        "Unit 2: Traditional Indian Games & Team Sports",
        "Unit 3: Yogic Practices, Asanas & Mindful Breathing",
        "Unit 4: Health, Nutrition, Hydration and Personal Hygiene",
        "Full Syllabus / Sports & Fitness"
      ],
    }
  },

  "Class 7": {
    subjects: {
      "Mathematics (Ganita Prakash / Mathematics)": [
        "Chapter 1: Integers",
        "Chapter 2: Fractions and Decimals",
        "Chapter 3: Data Handling",
        "Chapter 4: Simple Equations",
        "Chapter 5: Lines and Angles",
        "Chapter 6: The Triangle and Its Properties",
        "Chapter 7: Comparing Quantities",
        "Chapter 8: Rational Numbers",
        "Chapter 9: Perimeter and Area",
        "Chapter 10: Algebraic Expressions",
        "Chapter 11: Exponents and Powers",
        "Chapter 12: Symmetry",
        "Chapter 13: Visualising Solid Shapes",
        "Full Syllabus / Mixed Chapters"
      ],
      "Science (Curiosity / Science)": [
        "Chapter 1: Nutrition in Plants",
        "Chapter 2: Nutrition in Animals",
        "Chapter 3: Heat",
        "Chapter 4: Acids, Bases and Salts",
        "Chapter 5: Physical and Chemical Changes",
        "Chapter 6: Respiration in Organisms",
        "Chapter 7: Transportation in Animals and Plants",
        "Chapter 8: Reproduction in Plants",
        "Chapter 9: Motion and Time",
        "Chapter 10: Electric Current and Its Effects",
        "Chapter 11: Light",
        "Chapter 12: Forests: Our Lifeline",
        "Chapter 13: Wastewater Story",
        "Full Syllabus / Mixed Chapters"
      ],
      "Social Science (Exploring Society / NCERT)": [
        "History Ch 1: Tracing Changes Through a Thousand Years",
        "History Ch 2: Kings and Kingdoms",
        "History Ch 3: Delhi: 12th to 15th Century",
        "History Ch 4: The Mughals (16th to 17th Century)",
        "History Ch 5: Tribes, Nomads and Settled Communities",
        "History Ch 6: Devotional Paths to the Divine",
        "History Ch 7: The Making of Regional Cultures",
        "History Ch 8: Eighteenth-Century Political Formations",
        "Geography Ch 1: Environment",
        "Geography Ch 2: Inside Our Earth",
        "Geography Ch 3: Our Changing Earth",
        "Geography Ch 4: Air",
        "Geography Ch 5: Water",
        "Geography Ch 6: Human Environment Interactions",
        "Geography Ch 7: Life in the Deserts",
        "Civics Ch 1: On Equality",
        "Civics Ch 2: Role of the Government in Health",
        "Civics Ch 3: How the State Government Works",
        "Civics Ch 4: Growing up as Boys and Girls",
        "Civics Ch 5: Women Change the World",
        "Civics Ch 6: Understanding Media",
        "Civics Ch 7: Markets Around Us",
        "Civics Ch 8: A Shirt in the Market",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Honeycomb & An Alien Hand)": [
        "Honeycomb: Three Questions",
        "Honeycomb: A Gift of Chappals",
        "Honeycomb: Gopal and the Hilsa Fish",
        "Honeycomb: The Ashes That Made Trees Bloom",
        "Honeycomb: Quality",
        "Honeycomb: Expert Detectives",
        "Honeycomb: The Invention of Vita-Wonk",
        "Honeycomb: Meadow Surprises & Garden Snake",
        "An Alien Hand: The Tiny Teacher & Bringing Up Kari",
        "An Alien Hand: Golu Grows a Nose & Chandni",
        "An Alien Hand: The Bear Story & A Tiger in the House",
        "An Alien Hand: An Alien Hand",
        "Grammar: Tenses, Active-Passive Voice, Modals, Conjunctions",
        "Writing: Formal/Informal Letter, Story Writing, Diary Entry",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (वसंत भाग 2 / मल्हार)": [
        "पाठ 1: हम पंछी उन्मुक्त गगन के",
        "पाठ 2: हिमालय की बेटियाँ",
        "पाठ 3: कठपुतली",
        "पाठ 4: मिठाईवाला",
        "पाठ 5: पापा खो गए",
        "पाठ 6: शाम-एक किसान",
        "पाठ 7: अपूर्व अनुभव",
        "पाठ 8: रहीम के दोहे",
        "पाठ 9: एक तिनका",
        "पाठ 10: खानपान की बदलती तस्वीर",
        "पाठ 11: नीलकंठ",
        "पाठ 12: भोर और बरखा",
        "पाठ 13: वीर कुँवर सिंह",
        "पाठ 14: संघर्ष के कारण मैं तुनुकमिज़ाज हो गया: धनराज",
        "पाठ 15: आश्रम का अनुमानित व्यय",
        "व्याकरण: संधि, समास, उपसर्ग-प्रत्यय, मुहावरे, अपठित बोध",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Sanskrit (दीपकम / रुचिरा भाग 2)": [
        "पाठ 1: सुभाषितानि",
        "पाठ 2: दुर्बुद्धिः विनश्यति",
        "पाठ 3: स्वावलम्बनम्",
        "पाठ 4: पण्डिता रमाबाई",
        "पाठ 5: सदाचारः",
        "पाठ 6: सङ्कल्पः सिद्धिदायकः",
        "पाठ 7: त्रिवर्णः ध्वजः",
        "पाठ 8: अहम् अपि विद्यालयं गमिष्यामि",
        "पाठ 9: विश्वबन्धुत्वम्",
        "पाठ 10: समवायो हि दुर्जयः",
        "पाठ 11: विद्याधनम्",
        "पाठ 12: अमृतं संस्कृतम्",
        "व्याकरण: शब्दरूपाणि, धातुरूपाणि, कारक-विभक्तयः",
        "सम्पूर्ण पाठ्यक्रम"
      ],
    }
  },

  "Class 8": {
    subjects: {
      "Mathematics (Ganita Prakash / Mathematics)": [
        "Chapter 1: Rational Numbers",
        "Chapter 2: Linear Equations in One Variable",
        "Chapter 3: Understanding Quadrilaterals",
        "Chapter 4: Data Handling",
        "Chapter 5: Squares and Square Roots",
        "Chapter 6: Cubes and Cube Roots",
        "Chapter 7: Comparing Quantities",
        "Chapter 8: Algebraic Expressions and Identities",
        "Chapter 9: Mensuration",
        "Chapter 10: Exponents and Powers",
        "Chapter 11: Direct and Inverse Proportions",
        "Chapter 12: Factorisation",
        "Chapter 13: Introduction to Graphs",
        "Full Syllabus / Mixed Chapters"
      ],
      "Science (Curiosity / Science)": [
        "Chapter 1: Crop Production and Management",
        "Chapter 2: Microorganisms: Friend and Foe",
        "Chapter 3: Coal and Petroleum",
        "Chapter 4: Combustion and Flame",
        "Chapter 5: Conservation of Plants and Animals",
        "Chapter 6: Reproduction in Animals",
        "Chapter 7: Reaching the Age of Adolescence",
        "Chapter 8: Force and Pressure",
        "Chapter 9: Friction",
        "Chapter 10: Sound",
        "Chapter 11: Chemical Effects of Electric Current",
        "Chapter 12: Some Natural Phenomena",
        "Chapter 13: Light",
        "Full Syllabus / Mixed Chapters"
      ],
      "Social Science (Exploring Society / NCERT)": [
        "History Ch 1: How, When and Where",
        "History Ch 2: From Trade to Territory",
        "History Ch 3: Ruling the Countryside",
        "History Ch 4: Tribals, Dikus and the Vision of a Golden Age",
        "History Ch 5: When People Rebel 1857 and After",
        "History Ch 6: Civilising the 'Native', Educating the Nation",
        "History Ch 7: Women, Caste and Reform",
        "History Ch 8: The Making of the National Movement: 1870s–1947",
        "Geography Ch 1: Resources",
        "Geography Ch 2: Land, Soil, Water, Natural Vegetation and Wildlife",
        "Geography Ch 3: Agriculture",
        "Geography Ch 4: Industries",
        "Geography Ch 5: Human Resources",
        "Civics Ch 1: The Indian Constitution",
        "Civics Ch 2: Understanding Secularism",
        "Civics Ch 3: Parliament and the Making of Laws",
        "Civics Ch 4: Judiciary",
        "Civics Ch 5: Understanding Marginalisation",
        "Civics Ch 6: Confronting Marginalisation",
        "Civics Ch 7: Public Facilities",
        "Civics Ch 8: Law and Social Justice",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Honeydew & It So Happened)": [
        "Honeydew: The Best Christmas Present in the World",
        "Honeydew: The Tsunami",
        "Honeydew: Glimpses of the Past",
        "Honeydew: Bepin Choudhury's Lapse of Memory",
        "Honeydew: The Summit Within",
        "Honeydew: This is Jody's Fawn",
        "Honeydew: A Visit to Cambridge",
        "Honeydew: A Short Monsoon Diary",
        "Honeydew: On the Grasshopper and Cricket",
        "It So Happened: How the Camel Got His Hump",
        "It So Happened: Children at Work",
        "It So Happened: The Selfish Giant",
        "It So Happened: The Treasure Within",
        "It So Happened: Princess September",
        "It So Happened: The Fight",
        "It So Happened: Jalebis",
        "It So Happened: Ancient Education System of India",
        "Grammar: Reported Speech, Active/Passive Voice, Clauses, Modals",
        "Writing: Formal Letter, Article Writing, Notice Writing, Story",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (वसंत भाग 3 / भारत की खोज)": [
        "पाठ 1: ध्वनि",
        "पाठ 2: लाख की चूड़ियाँ",
        "पाठ 3: बस की यात्रा",
        "पाठ 4: दीवानों की हस्ती",
        "पाठ 5: चिट्ठियों की अनूठी दुनिया",
        "पाठ 6: भगवान के डाकिए",
        "पाठ 7: क्या निराश हुआ जाए",
        "पाठ 8: यह सबसे कठिन समय नहीं",
        "पाठ 9: कबीर की साखियाँ",
        "पाठ 10: कामचोर",
        "पाठ 11: जब सिनेमा ने बोलना सीखा",
        "पाठ 12: सुदामा चरित",
        "पाठ 13: जहाँ पहिया है",
        "पाठ 14: अकबरी लोटा",
        "पाठ 15: सूर के पद",
        "पाठ 16: पानी की कहानी",
        "पाठ 17: बाज और साँप",
        "पाठ 18: टोपी",
        "भारत की खोज: अहमदनगर का किला, तलाश, सिंधु घाटी सभ्यता, युगों का दौर",
        "व्याकरण: रस, छंद, अलंकार, समास, पदबंध, मुहावरे, अपठित बोध",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Sanskrit (रुचिरा भाग 3)": [
        "पाठ 1: सुभाषितानि",
        "पाठ 2: बिलस्य वाणी न कदापि मे श्रुता",
        "पाठ 3: डिजीभारतम्",
        "पाठ 4: सदैव पुरतो निधेहि चरणम्",
        "पाठ 5: कण्टकेनैव कण्टकम्",
        "पाठ 6: गृहं शून्यं सुतां विना",
        "पाठ 7: भारतजनताऽहम्",
        "पाठ 8: संसारसागरस्य नायकाः",
        "पाठ 9: सप्तभगिन्यः",
        "पाठ 10: नीतिनवनीतम्",
        "पाठ 11: सावित्री बाई फुले",
        "पाठ 12: कः रक्षति कः रक्षितः",
        "पाठ 13: क्षितौ राजते भारतस्वर्णभूमिः",
        "पाठ 14: आर्यभटः",
        "व्याकरण: सन्धिः, समासः, प्रत्ययाः, कारक-विभक्तयः",
        "सम्पूर्ण पाठ्यक्रम"
      ],
    }
  },

  "Class 9": {
    subjects: {
      "Mathematics (Ganita Manjari / NCERT Rationalized)": [
        "Chapter 1: Number Systems",
        "Chapter 2: Polynomials",
        "Chapter 3: Coordinate Geometry",
        "Chapter 4: Linear Equations in Two Variables",
        "Chapter 5: Introduction to Euclid's Geometry",
        "Chapter 6: Lines and Angles",
        "Chapter 7: Triangles",
        "Chapter 8: Quadrilaterals",
        "Chapter 9: Circles",
        "Chapter 10: Heron's Formula",
        "Chapter 11: Surface Areas and Volumes",
        "Chapter 12: Statistics",
        "Full Syllabus / Mixed Chapters"
      ],
      "Science (Exploration / Vigyan Rationalized)": [
        "Chapter 1: Matter in Our Surroundings",
        "Chapter 2: Is Matter Around Us Pure",
        "Chapter 3: Atoms and Molecules",
        "Chapter 4: Structure of the Atom",
        "Chapter 5: The Fundamental Unit of Life",
        "Chapter 6: Tissues",
        "Chapter 7: Motion",
        "Chapter 8: Force and Laws of Motion",
        "Chapter 9: Gravitation",
        "Chapter 10: Work and Energy",
        "Chapter 11: Sound",
        "Chapter 12: Improvement in Food Resources",
        "Full Syllabus / Mixed Chapters"
      ],
      "Social Science (Understanding Society / NCERT)": [
        "History Ch 1: The French Revolution",
        "History Ch 2: Socialism in Europe and the Russian Revolution",
        "History Ch 3: Nazism and the Rise of Hitler",
        "History Ch 4: Forest Society and Colonialism",
        "History Ch 5: Pastoralists in the Modern World",
        "Geography Ch 1: India – Size and Location",
        "Geography Ch 2: Physical Features of India",
        "Geography Ch 3: Drainage",
        "Geography Ch 4: Climate",
        "Geography Ch 5: Natural Vegetation and Wildlife",
        "Geography Ch 6: Population",
        "Pol Science Ch 1: What is Democracy? Why Democracy?",
        "Pol Science Ch 2: Constitutional Design",
        "Pol Science Ch 3: Electoral Politics",
        "Pol Science Ch 4: Working of Institutions",
        "Pol Science Ch 5: Democratic Rights",
        "Economics Ch 1: The Story of Village Palampur",
        "Economics Ch 2: People as Resource",
        "Economics Ch 3: Poverty as a Challenge",
        "Economics Ch 4: Food Security in India",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (Beehive, Moments / Kaveri)": [
        "Beehive: The Fun They Had & The Road Not Taken",
        "Beehive: The Sound of Music & Wind",
        "Beehive: The Little Girl & Rain on the Roof",
        "Beehive: A Truly Beautiful Mind & The Lake Isle of Innisfree",
        "Beehive: The Snake and the Mirror & A Legend of the Northland",
        "Beehive: My Childhood & No Men Are Foreign",
        "Beehive: Reach for the Top & On Killing a Tree",
        "Beehive: Kathmandu & A Slumber Did My Spirit Seal",
        "Beehive: If I Were You",
        "Moments: The Lost Child",
        "Moments: The Adventures of Toto",
        "Moments: Iswaran the Storyteller",
        "Moments: In the Kingdom of Fools",
        "Moments: The Happy Prince",
        "Moments: The Last Leaf",
        "Moments: A House is Not a Home",
        "Moments: The Beggar",
        "Grammar: Tenses, Modals, Subject-Verb Concord, Reported Speech",
        "Writing: Descriptive Paragraph (Person/Event/Situation), Story Writing",
        "Reading: Discursive & Case-based Factual Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (क्षितिज / स्पर्श / कृतिका / संचयन)": [
        "क्षितिज गद्य: दो बैलों की कथा (प्रेमचंद)",
        "क्षितिज गद्य: ल्हासा की ओर (राहुल सांकृत्यायन)",
        "क्षितिज गद्य: उपभोक्तावाद की संस्कृति (श्यामाचरण दुबे)",
        "क्षितिज गद्य: साँवले सपनों की याद (जाबिर हुसैन)",
        "क्षितिज गद्य: प्रेमचंद के फटे जूते (हरिशंकर परसाई)",
        "क्षितिज गद्य: मेरे बचपन के दिन (महादेवी वर्मा)",
        "क्षितिज काव्य: साखियाँ एवं सबद (कबीर)",
        "क्षितिज काव्य: वाख (ललद्यद)",
        "क्षितिज काव्य: सवैये (रसखान)",
        "क्षितिज काव्य: कैदी और कोकिला (माखनलाल चतुर्वेदी)",
        "क्षितिज काव्य: ग्राम श्री (सुमित्रानंदन पंत)",
        "क्षितिज काव्य: मेघ आए (सर्वेश्वर दयाल सक्सेना)",
        "क्षितिज काव्य: बच्चे काम पर जा रहे हैं (राजेश जोशी)",
        "कृतिका: इस जल प्रलय में, मेरे संग की औरतें, रीढ़ की हड्डी",
        "स्पर्श: दुःख का अधिकार, एवरेस्ट: मेरी शिखर यात्रा, तुम कब जाओगे अतिथि, शुक्रतारे के समान",
        "व्याकरण: उपसर्ग-प्रत्यय, समास, अर्थ की दृष्टि से वाक्य भेद, अलंकार",
        "रचनात्मक लेखन: अनुच्छेद लेखन, पत्र लेखन, संवाद लेखन, लघु कथा",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Sanskrit (शेमुषी भाग 1 / शारदा)": [
        "पाठ 1: भारतीवसन्तगीतिः",
        "पाठ 2: स्वर्णकाकः",
        "पाठ 3: गोदोहनम्",
        "पाठ 4: सूक्तिमौक्तिकम्",
        "पाठ 5: भ्रान्तो बालः",
        "पाठ 6: लौहतुला",
        "पाठ 7: सिकतासेतुः",
        "पाठ 8: जटायोः शौर्यम्",
        "पाठ 9: पर्यावरणम्",
        "पाठ 10: वाङ्मनःप्राणस्वरूपम्",
        "व्याकरण: सन्धिः, शब्दरूपाणि, धातुरूपाणि, उपपदविभक्तयः, प्रत्ययाः",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Information Technology (Code 402)": [
        "Part A: Employability Skills (Communication, Self-Management, ICT Skills)",
        "Part B Unit 1: Introduction to IT-ITeS Industry",
        "Part B Unit 2: Data Entry & Keyboarding Skills",
        "Part B Unit 3: Digital Documentation (LibreOffice Writer / MS Word)",
        "Part B Unit 4: Electronic Spreadsheet (LibreOffice Calc / MS Excel)",
        "Part B Unit 5: Digital Presentation (LibreOffice Impress / MS PowerPoint)",
        "Full Syllabus / Practical & Theory"
      ],
    }
  },

  "Class 10": {
    subjects: {
      "Mathematics (NCERT Rationalized)": [
        "Chapter 1: Real Numbers",
        "Chapter 2: Polynomials",
        "Chapter 3: Pair of Linear Equations in Two Variables",
        "Chapter 4: Quadratic Equations",
        "Chapter 5: Arithmetic Progressions",
        "Chapter 6: Triangles",
        "Chapter 7: Coordinate Geometry",
        "Chapter 8: Introduction to Trigonometry",
        "Chapter 9: Some Applications of Trigonometry (Heights and Distances)",
        "Chapter 10: Circles",
        "Chapter 11: Areas Related to Circles",
        "Chapter 12: Surface Areas and Volumes",
        "Chapter 13: Statistics",
        "Chapter 14: Probability",
        "Full Syllabus / Mixed Chapters"
      ],
      "Science (NCERT Rationalized)": [
        "Chapter 1: Chemical Reactions and Equations",
        "Chapter 2: Acids, Bases and Salts",
        "Chapter 3: Metals and Non-metals",
        "Chapter 4: Carbon and its Compounds",
        "Chapter 5: Life Processes",
        "Chapter 6: Control and Coordination",
        "Chapter 7: How do Organisms Reproduce?",
        "Chapter 8: Heredity",
        "Chapter 9: Light – Reflection and Refraction",
        "Chapter 10: The Human Eye and the Colourful World",
        "Chapter 11: Electricity",
        "Chapter 12: Magnetic Effects of Electric Current",
        "Chapter 13: Our Environment",
        "Full Syllabus / Mixed Chapters"
      ],
      "Social Science (NCERT Rationalized)": [
        "History Ch 1: The Rise of Nationalism in Europe",
        "History Ch 2: Nationalism in India",
        "History Ch 3: The Making of a Global World",
        "History Ch 4: The Age of Industrialisation",
        "History Ch 5: Print Culture and the Modern World",
        "Geography Ch 1: Resources and Development",
        "Geography Ch 2: Forest and Wildlife Resources",
        "Geography Ch 3: Water Resources",
        "Geography Ch 4: Agriculture",
        "Geography Ch 5: Minerals and Energy Resources",
        "Geography Ch 6: Manufacturing Industries",
        "Geography Ch 7: Lifelines of National Economy",
        "Pol Science Ch 1: Power-sharing",
        "Pol Science Ch 2: Federalism",
        "Pol Science Ch 3: Gender, Religion and Caste",
        "Pol Science Ch 4: Political Parties",
        "Pol Science Ch 5: Outcomes of Democracy",
        "Economics Ch 1: Development",
        "Economics Ch 2: Sectors of the Indian Economy",
        "Economics Ch 3: Money and Credit",
        "Economics Ch 4: Globalisation and the Indian Economy",
        "Economics Ch 5: Consumer Rights",
        "Full Syllabus / Mixed Chapters"
      ],
      "English (First Flight & Footprints Without Feet)": [
        "First Flight: A Letter to God & Dust of Snow / Fire and Ice",
        "First Flight: Nelson Mandela: Long Walk to Freedom & A Tiger in the Zoo",
        "First Flight: Two Stories About Flying & How to Tell Wild Animals / The Ball Poem",
        "First Flight: From the Diary of Anne Frank & Amanda!",
        "First Flight: Glimpses of India & The Trees",
        "First Flight: Mijbil the Otter & Fog",
        "First Flight: Madam Rides the Bus & The Tale of Custard the Dragon",
        "First Flight: The Sermon at Benares & For Anne Gregory",
        "First Flight: The Proposal (Play by Anton Chekhov)",
        "Footprints: A Triumph of Surgery",
        "Footprints: The Thief's Story",
        "Footprints: The Midnight Visitor",
        "Footprints: A Question of Trust",
        "Footprints: Footprints Without Feet",
        "Footprints: The Making of a Scientist",
        "Footprints: The Necklace",
        "Footprints: Bholi",
        "Footprints: The Book That Saved the Earth",
        "Grammar: Tenses, Modals, Subject-Verb Concord, Reported Speech",
        "Writing: Formal Letter (Editor/Complaint/Order), Analytical Paragraph",
        "Reading: Discursive & Case-based Factual Passages",
        "Full Syllabus / Mixed Chapters"
      ],
      "Hindi (क्षितिज-2 / स्पर्श-2 / कृतिका-2 / संचयन-2)": [
        "क्षितिज गद्य: नेताजी का चश्मा (स्वयं प्रकाश)",
        "क्षितिज गद्य: बालगोबिन भगत (रामवृक्ष बेनीपुरी)",
        "क्षितिज गद्य: लखनवी अंदाज़ (यशपाल)",
        "क्षितिज गद्य: एक कहानी यह भी (मन्नू भंडारी)",
        "क्षितिज गद्य: नौबतखाने में इबादत (यतींद्र मिश्र)",
        "क्षितिज गद्य: संस्कृति (भदंत आनंद कौसल्यायन)",
        "क्षितिज काव्य: पद (सूरदास)",
        "क्षितिज काव्य: राम-लक्ष्मण-परशुराम संवाद (तुलसीदास)",
        "क्षितिज काव्य: आत्मकथ्य (जयशंकर प्रसाद)",
        "क्षितिज काव्य: उत्साह एवं अट नहीं रही है (सूर्यकांत त्रिपाठी 'निराला')",
        "क्षितिज काव्य: यह दंतुरहित मुस्कान एवं फसल (नागार्जुन)",
        "क्षितिज काव्य: संगतकार (मंगलेश डबराल)",
        "कृतिका: माता का अँचल, साना-साना हाथ जोड़ि, मैं क्यों लिखता हूँ?",
        "स्पर्श: साखी (कबीर), पद (मीरा), बिहारी के दोहे, मनुष्यता, पर्वत प्रदेश में पावस, तोप, कर चले हम फ़िदा, आत्मत्राण",
        "स्पर्श गद्य: बड़े भाई साहब, डायरी का एक पन्ना, तँतारा-वामीरो कथा, तीसरी कसम के शिल्पकार, अब कहाँ दूसरे के दुख से दुखी होने वाले, पतझर में टूटी पत्तियाँ, कारतूस",
        "व्याकरण: रचना के आधार पर वाक्य भेद, वाच्य, पद-परिचय, रस",
        "रचनात्मक लेखन: अनुच्छेद लेखन, औपचारिक/अनौपचारिक पत्र, स्ववृत्त लेखन/ई-मेल, विज्ञापन/संदेश लेखन",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Sanskrit (शेमुषी भाग 2 / मणिका)": [
        "पाठ 1: शुचिपर्यावरणम्",
        "पाठ 2: बुद्धिर्बलवती सदा",
        "पाठ 3: जननी तुल्यवत्सला",
        "पाठ 4: सुभाषितानि",
        "पाठ 5: सौहार्दं प्रकृतेः शोभा",
        "पाठ 6: विचित्रः साक्षी",
        "पाठ 7: सूक्तयः",
        "पाठ 8: अन्योक्तयः",
        "व्याकरण: सन्धिः (व्यञ्जन, विसर्ग), समासाः (तत्पुरुष, बहुव्रीहि, द्वन्द्व), प्रत्ययाः (मतुप्, तल्, त्व)",
        "व्याकरण: वाच्यपरिवर्तनम्, अव्ययानि, अशुद्धिसंशोधनम्, पत्रलेखनम्, चित्रवर्णनम्",
        "सम्पूर्ण पाठ्यक्रम"
      ],
      "Information Technology (Code 402)": [
        "Part A: Employability Skills (Communication, Self-Management, ICT, Entrepreneurial, Green Skills)",
        "Part B Unit 1: Digital Documentation (Advanced)",
        "Part B Unit 2: Electronic Spreadsheet (Advanced)",
        "Part B Unit 3: Database Management System (DBMS / SQL)",
        "Part B Unit 4: Web Applications and Security",
        "Full Syllabus / Practical & Theory"
      ],
    }
  },

  "Class 11 Science": {
    subjects: {
      "Physics (Part I & II Rationalized)": [
        "Chapter 1: Units and Measurements",
        "Chapter 2: Motion in a Straight Line",
        "Chapter 3: Motion in a Plane",
        "Chapter 4: Laws of Motion",
        "Chapter 5: Work, Energy and Power",
        "Chapter 6: System of Particles and Rotational Motion",
        "Chapter 7: Gravitation",
        "Chapter 8: Mechanical Properties of Solids",
        "Chapter 9: Mechanical Properties of Fluids",
        "Chapter 10: Thermal Properties of Matter",
        "Chapter 11: Thermodynamics",
        "Chapter 12: Kinetic Theory",
        "Chapter 13: Oscillations",
        "Chapter 14: Waves",
        "Full Syllabus / Mixed Chapters"
      ],
      "Chemistry (Part I & II Rationalized)": [
        "Chapter 1: Some Basic Concepts of Chemistry",
        "Chapter 2: Structure of Atom",
        "Chapter 3: Classification of Elements and Periodicity in Properties",
        "Chapter 4: Chemical Bonding and Molecular Structure",
        "Chapter 5: Chemical Thermodynamics",
        "Chapter 6: Equilibrium",
        "Chapter 7: Redox Reactions",
        "Chapter 8: Organic Chemistry: Some Basic Principles and Techniques",
        "Chapter 9: Hydrocarbons",
        "Full Syllabus / Mixed Chapters"
      ],
      "Biology (NCERT Rationalized)": [
        "Chapter 1: The Living World",
        "Chapter 2: Biological Classification",
        "Chapter 3: Plant Kingdom",
        "Chapter 4: Animal Kingdom",
        "Chapter 5: Morphology of Flowering Plants",
        "Chapter 6: Anatomy of Flowering Plants",
        "Chapter 7: Structural Organisation in Animals",
        "Chapter 8: Cell: The Unit of Life",
        "Chapter 9: Biomolecules",
        "Chapter 10: Cell Cycle and Cell Division",
        "Chapter 11: Photosynthesis in Higher Plants",
        "Chapter 12: Respiration in Plants",
        "Chapter 13: Plant Growth and Development",
        "Chapter 14: Breathing and Exchange of Gases",
        "Chapter 15: Body Fluids and Circulation",
        "Chapter 16: Excretory Products and their Elimination",
        "Chapter 17: Locomotion and Movement",
        "Chapter 18: Neural Control and Coordination",
        "Chapter 19: Chemical Coordination and Integration",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics (NCERT Rationalized)": [
        "Chapter 1: Sets",
        "Chapter 2: Relations and Functions",
        "Chapter 3: Trigonometric Functions",
        "Chapter 4: Complex Numbers and Quadratic Equations",
        "Chapter 5: Linear Inequalities",
        "Chapter 6: Permutations and Combinations",
        "Chapter 7: Binomial Theorem",
        "Chapter 8: Sequences and Series",
        "Chapter 9: Straight Lines",
        "Chapter 10: Conic Sections",
        "Chapter 11: Introduction to Three Dimensional Geometry",
        "Chapter 12: Limits and Derivatives",
        "Chapter 13: Statistics",
        "Chapter 14: Probability",
        "Full Syllabus / Mixed Chapters"
      ],
      "Computer Science (Code 083)": [
        "Unit 1: Computer Systems and Organisation",
        "Unit 2: Computational Thinking and Programming - 1 (Python Basics, Conditionals, Loops, Strings, Lists, Tuples, Dictionaries)",
        "Unit 3: Society, Law and Ethics (Cyber Safety, Digital Footprint, Cyber Crime, IT Act)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Hornbill & Snapshots)": [
        "Hornbill: The Portrait of a Lady & A Photograph",
        "Hornbill: We're Not Afraid to Die... If We Can All Be Together",
        "Hornbill: Discovering Tut: the Saga Continues & The Laburnum Top",
        "Hornbill: The Voice of the Rain",
        "Hornbill: Childhood",
        "Hornbill: The Adventure",
        "Hornbill: Silk Road & Father to Son",
        "Snapshots: The Summer of the Beautiful White Horse",
        "Snapshots: The Address",
        "Snapshots: Mother's Day",
        "Snapshots: Birth",
        "Snapshots: The Tale of Melon City",
        "Grammar & Creative Writing: Note Making, Summarizing, Poster Making, Speech, Debate",
        "Reading: Unseen Passages (Comprehension & Note-Making)",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 11 Commerce": {
    subjects: {
      "Accountancy (Financial Accounting I & II)": [
        "Chapter 1: Introduction to Accounting",
        "Chapter 2: Theory Base of Accounting & Accounting Standards",
        "Chapter 3: Recording of Transactions - I (Vouchers, Journal, Ledger)",
        "Chapter 4: Recording of Transactions - II (Cash Book & Other Books)",
        "Chapter 5: Bank Reconciliation Statement (BRS)",
        "Chapter 6: Trial Balance and Rectification of Errors",
        "Chapter 7: Depreciation, Provisions and Reserves",
        "Chapter 8: Financial Statements - I (Without Adjustments)",
        "Chapter 9: Financial Statements - II (With Adjustments)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Business Studies (Foundation of Business)": [
        "Chapter 1: Evolution and Fundamentals of Business",
        "Chapter 2: Forms of Business Organisations",
        "Chapter 3: Public, Private and Global Enterprises",
        "Chapter 4: Business Services (Banking, Insurance, Communication)",
        "Chapter 5: Emerging Modes of Business (e-Business, Outsourcing)",
        "Chapter 6: Social Responsibility of Business and Business Ethics",
        "Chapter 7: Sources of Business Finance",
        "Chapter 8: Small Business and Enterprises",
        "Chapter 9: Internal Trade (Wholesale, Retail, GST Basics)",
        "Chapter 10: International Business",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics (Statistics & Indian Economic Development)": [
        "Statistics Ch 1: Introduction",
        "Statistics Ch 2: Collection of Data",
        "Statistics Ch 3: Organisation of Data",
        "Statistics Ch 4: Presentation of Data (Tables & Graphs)",
        "Statistics Ch 5: Measures of Central Tendency (Mean, Median, Mode)",
        "Statistics Ch 6: Correlation",
        "Statistics Ch 7: Index Numbers",
        "Dev Ch 1: Indian Economy on the Eve of Independence",
        "Dev Ch 2: Indian Economy (1950–1990)",
        "Dev Ch 3: Liberalisation, Privatisation and Globalisation (LPG Reforms)",
        "Dev Ch 4: Human Capital Formation in India",
        "Dev Ch 5: Rural Development",
        "Dev Ch 6: Employment: Growth, Informalisation and Other Issues",
        "Dev Ch 7: Sustainable Economic Development",
        "Dev Ch 8: Development Experiences of India: A Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics (Core / Applied Mathematics)": [
        "Chapter 1: Sets and Relations",
        "Chapter 2: Functions and Trigonometry",
        "Chapter 3: Complex Numbers and Quadratic Equations",
        "Chapter 4: Linear Inequalities",
        "Chapter 5: Permutations and Combinations",
        "Chapter 6: Sequences and Series",
        "Chapter 7: Straight Lines and Conic Sections",
        "Chapter 8: Limits, Derivatives & Calculus",
        "Chapter 9: Statistics and Probability",
        "Applied Math: Financial Mathematics (Annuity, EMI, Depreciation)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Informatics Practices (Code 065)": [
        "Unit 1: Introduction to Computer System",
        "Unit 2: Introduction to Python (Basics, Data Types, Control Structures, Lists, Dictionaries)",
        "Unit 3: Database Concepts and Structured Query Language (SQL)",
        "Unit 4: Emerging Trends (AI, IoT, Cloud Computing, Blockchain)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Hornbill & Snapshots)": [
        "Hornbill: The Portrait of a Lady & A Photograph",
        "Hornbill: We're Not Afraid to Die... If We Can All Be Together",
        "Hornbill: Discovering Tut: the Saga Continues & The Laburnum Top",
        "Hornbill: The Voice of the Rain & Childhood",
        "Hornbill: The Adventure & Silk Road & Father to Son",
        "Snapshots: The Summer of the Beautiful White Horse & The Address",
        "Snapshots: Mother's Day & Birth & The Tale of Melon City",
        "Grammar & Writing: Poster Making, Speech, Debate, Letter Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 11 Humanities": {
    subjects: {
      "History (Themes in World History Rationalized)": [
        "Theme 1: Writing and City Life (Mesopotamia)",
        "Theme 2: An Empire Across Three Continents (Roman Empire)",
        "Theme 3: Nomadic Empires (Mongols)",
        "Theme 4: The Three Orders (Western Europe 9th-16th Century)",
        "Theme 5: Changing Cultural Traditions (Renaissance)",
        "Theme 6: Displacing Indigenous Peoples",
        "Theme 7: Paths to Modernisation (Japan and China)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Political Science (NCERT Rationalized)": [
        "Part A Ch 1: Constitution: Why and How?",
        "Part A Ch 2: Rights in the Indian Constitution",
        "Part A Ch 3: Election and Representation",
        "Part A Ch 4: Executive",
        "Part A Ch 5: Legislature",
        "Part A Ch 6: Judiciary",
        "Part A Ch 7: Federalism",
        "Part A Ch 8: Local Governments",
        "Part B Ch 1: Political Theory: An Introduction",
        "Part B Ch 2: Freedom",
        "Part B Ch 3: Equality",
        "Part B Ch 4: Social Justice",
        "Part B Ch 5: Rights",
        "Part B Ch 6: Citizenship",
        "Part B Ch 7: Nationalism",
        "Part B Ch 8: Secularism",
        "Full Syllabus / Mixed Chapters"
      ],
      "Geography (Physical & Indian Environment)": [
        "Fundamentals Ch 1: Geography as a Discipline",
        "Fundamentals Ch 2: The Origin and Evolution of the Earth",
        "Fundamentals Ch 3: Interior of the Earth",
        "Fundamentals Ch 4: Distribution of Oceans and Continents",
        "Fundamentals Ch 5: Geomorphic Processes",
        "Fundamentals Ch 6: Landforms and their Evolution",
        "Fundamentals Ch 7: Composition and Structure of Atmosphere",
        "Fundamentals Ch 8: Solar Radiation, Heat Balance and Temperature",
        "Fundamentals Ch 9: Atmospheric Circulation and Weather Systems",
        "Fundamentals Ch 10: Water in the Atmosphere",
        "Fundamentals Ch 11: World Climate and Climate Change",
        "Fundamentals Ch 12: Water (Oceans)",
        "Fundamentals Ch 13: Movements of Ocean Water",
        "Fundamentals Ch 14: Biodiversity and Conservation",
        "India Ch 1: India – Location",
        "India Ch 2: Structure and Physiography",
        "India Ch 3: Drainage System",
        "India Ch 4: Climate",
        "India Ch 5: Natural Vegetation",
        "India Ch 6: Soils",
        "India Ch 7: Natural Hazards and Disasters",
        "Full Syllabus / Mixed Chapters"
      ],
      "Psychology (Introduction to Psychology)": [
        "Chapter 1: What is Psychology?",
        "Chapter 2: Methods of Enquiry in Psychology",
        "Chapter 3: Human Development",
        "Chapter 4: Sensory, Attentional and Perceptual Processes",
        "Chapter 5: Learning",
        "Chapter 6: Human Memory",
        "Chapter 7: Thinking",
        "Chapter 8: Motivation and Emotion",
        "Full Syllabus / Mixed Chapters"
      ],
      "Sociology (Introducing Sociology & Understanding Society)": [
        "Book 1 Ch 1: Sociology and Society",
        "Book 1 Ch 2: Terms, Concepts and their Use in Sociology",
        "Book 1 Ch 3: Understanding Social Institutions",
        "Book 1 Ch 4: Culture and Socialisation",
        "Book 1 Ch 5: Doing Sociology: Research Methods",
        "Book 2 Ch 1: Social Structure, Stratification and Social Processes",
        "Book 2 Ch 2: Social Change and Social Order in Rural and Urban Society",
        "Book 2 Ch 3: Environment and Society",
        "Book 2 Ch 4: Introducing Western Sociologists",
        "Book 2 Ch 5: Indian Sociologists",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics (Statistics & Indian Economic Development)": [
        "Statistics: Collection, Organisation & Presentation of Data",
        "Statistics: Measures of Central Tendency (Mean, Median, Mode)",
        "Statistics: Correlation & Index Numbers",
        "Indian Economy: Eve of Independence & 1950–1990",
        "Indian Economy: Economic Reforms Since 1991 (LPG)",
        "Indian Economy: Current Challenges (Human Capital, Rural Development, Employment)",
        "Indian Economy: Sustainable Development & Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Hornbill & Snapshots)": [
        "Hornbill: The Portrait of a Lady, We're Not Afraid to Die, Discovering Tut, Silk Road",
        "Hornbill Poetry: A Photograph, The Laburnum Top, The Voice of the Rain, Childhood, Father to Son",
        "Snapshots: The Summer of the Beautiful White Horse, The Address, Mother's Day, Birth, The Tale of Melon City",
        "Writing & Grammar: Note-Making, Poster Making, Speech, Debate",
        "Reading Comprehension",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 12 Science": {
    subjects: {
      "Physics (Part I & II Rationalized)": [
        "Chapter 1: Electric Charges and Fields",
        "Chapter 2: Electrostatic Potential and Capacitance",
        "Chapter 3: Current Electricity",
        "Chapter 4: Moving Charges and Magnetism",
        "Chapter 5: Magnetism and Matter",
        "Chapter 6: Electromagnetic Induction",
        "Chapter 7: Alternating Current",
        "Chapter 8: Electromagnetic Waves",
        "Chapter 9: Ray Optics and Optical Instruments",
        "Chapter 10: Wave Optics",
        "Chapter 11: Dual Nature of Radiation and Matter",
        "Chapter 12: Atoms",
        "Chapter 13: Nuclei",
        "Chapter 14: Semiconductor Electronics: Materials, Devices and Simple Circuits",
        "Full Syllabus / Mixed Chapters"
      ],
      "Chemistry (Part I & II Rationalized)": [
        "Chapter 1: Solutions",
        "Chapter 2: Electrochemistry",
        "Chapter 3: Chemical Kinetics",
        "Chapter 4: The d- and f-Block Elements",
        "Chapter 5: Coordination Compounds",
        "Chapter 6: Haloalkanes and Haloarenes",
        "Chapter 7: Alcohols, Phenols and Ethers",
        "Chapter 8: Aldehydes, Ketones and Carboxylic Acids",
        "Chapter 9: Amines",
        "Chapter 10: Biomolecules",
        "Full Syllabus / Mixed Chapters"
      ],
      "Biology (NCERT Rationalized)": [
        "Chapter 1: Sexual Reproduction in Flowering Plants",
        "Chapter 2: Human Reproduction",
        "Chapter 3: Reproductive Health",
        "Chapter 4: Principles of Inheritance and Variation",
        "Chapter 5: Molecular Basis of Inheritance",
        "Chapter 6: Evolution",
        "Chapter 7: Human Health and Disease",
        "Chapter 8: Microbes in Human Welfare",
        "Chapter 9: Biotechnology: Principles and Processes",
        "Chapter 10: Biotechnology and its Applications",
        "Chapter 11: Organisms and Populations",
        "Chapter 12: Ecosystem",
        "Chapter 13: Biodiversity and Conservation",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics (Part I & II Rationalized)": [
        "Chapter 1: Relations and Functions",
        "Chapter 2: Inverse Trigonometric Functions",
        "Chapter 3: Matrices",
        "Chapter 4: Determinants",
        "Chapter 5: Continuity and Differentiability",
        "Chapter 6: Application of Derivatives",
        "Chapter 7: Integrals",
        "Chapter 8: Application of Integrals",
        "Chapter 9: Differential Equations",
        "Chapter 10: Vector Algebra",
        "Chapter 11: Three Dimensional Geometry",
        "Chapter 12: Linear Programming",
        "Chapter 13: Probability",
        "Full Syllabus / Mixed Chapters"
      ],
      "Computer Science (Code 083)": [
        "Unit 1: Computational Thinking and Programming - 2 (Python Revision, Functions, File Handling: Text, Binary, CSV)",
        "Unit 1: Data Structure: Stack using Python List",
        "Unit 2: Computer Networks (Evolution, Topologies, Protocols, Network Security)",
        "Unit 3: Database Management (SQL Queries, Aggregate Functions, Joins, Python-SQL Interface)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Flamingo & Vistas)": [
        "Flamingo Prose: The Last Lesson (Alphonse Daudet)",
        "Flamingo Prose: Lost Spring (Anees Jung)",
        "Flamingo Prose: Deep Water (William Douglas)",
        "Flamingo Prose: The Rattrap (Selma Lagerlöf)",
        "Flamingo Prose: Indigo (Louis Fischer)",
        "Flamingo Prose: Poets and Pancakes (Asokamitran)",
        "Flamingo Prose: The Interview (Christopher Silvester)",
        "Flamingo Prose: Going Places (A. R. Barton)",
        "Flamingo Poetry: My Mother at Sixty-six (Kamala Das)",
        "Flamingo Poetry: Keeping Quiet (Pablo Neruda)",
        "Flamingo Poetry: A Thing of Beauty (John Keats)",
        "Flamingo Poetry: A Roadside Stand (Robert Frost)",
        "Flamingo Poetry: Aunt Jennifer's Tigers (Adrienne Rich)",
        "Vistas: The Third Level (Jack Finney)",
        "Vistas: The Tiger King (Kalki)",
        "Vistas: Journey to the End of the Earth (Tishani Doshi)",
        "Vistas: The Enemy (Pearl S. Buck)",
        "Vistas: On the Face of It (Susan Hill)",
        "Vistas: Memories of Childhood (Zitkala-Sa & Bama)",
        "Writing Skills: Notice Writing, Invitations and Replies, Formal Letter (Job Application / Editor), Article / Report Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 12 Commerce": {
    subjects: {
      "Accountancy (Partnership & Companies Rationalized)": [
        "Part A Ch 1: Accounting for Partnership: Basic Concepts",
        "Part A Ch 2: Goodwill: Nature and Valuation",
        "Part A Ch 3: Change in Profit-Sharing Ratio Among Existing Partners",
        "Part A Ch 4: Admission of a Partner",
        "Part A Ch 5: Retirement and Death of a Partner",
        "Part A Ch 6: Dissolution of a Partnership Firm",
        "Part B Ch 1: Accounting for Share Capital (Issue, Forfeiture, Reissue)",
        "Part B Ch 2: Issue and Redemption of Debentures",
        "Part B Ch 3: Financial Statements of a Company",
        "Part B Ch 4: Analysis of Financial Statements (Comparative & Common Size)",
        "Part B Ch 5: Accounting Ratios (Liquidity, Solvency, Activity, Profitability)",
        "Part B Ch 6: Cash Flow Statement (AS-3 Revised)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Business Studies (Principles & Functions of Management)": [
        "Part I Ch 1: Nature and Significance of Management",
        "Part I Ch 2: Principles of Management (Fayol & Taylor)",
        "Part I Ch 3: Business Environment",
        "Part I Ch 4: Planning",
        "Part I Ch 5: Organising",
        "Part I Ch 6: Staffing",
        "Part I Ch 7: Directing",
        "Part I Ch 8: Controlling",
        "Part II Ch 9: Financial Management",
        "Part II Ch 10: Financial Markets (Money & Capital Market)",
        "Part II Ch 11: Marketing Management",
        "Part II Ch 12: Consumer Protection (CPA 2019)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics (Macroeconomics & Indian Economic Development)": [
        "Macro Ch 1: Introduction to Macroeconomics",
        "Macro Ch 2: National Income Accounting and Related Aggregates",
        "Macro Ch 3: Money and Banking (Commercial & Central Bank)",
        "Macro Ch 4: Determination of Income and Employment (AD-AS, Multiplier)",
        "Macro Ch 5: Government Budget and the Economy",
        "Macro Ch 6: Balance of Payments and Foreign Exchange Rate",
        "Dev Ch 1: Development Experience (1947–90) and Economic Reforms since 1991",
        "Dev Ch 2: Current Challenges Facing Indian Economy (Human Capital, Rural Development)",
        "Dev Ch 3: Employment, Infrastructure and Sustainable Development",
        "Dev Ch 4: Development Experience of India: A Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics (Core / Applied Mathematics)": [
        "Chapter 1: Relations and Functions & Inverse Trigonometry",
        "Chapter 2: Matrices and Determinants",
        "Chapter 3: Continuity, Differentiability & Derivatives",
        "Chapter 4: Applications of Derivatives",
        "Chapter 5: Integrals and Application of Integrals",
        "Chapter 6: Differential Equations",
        "Chapter 7: Vector Algebra and Three Dimensional Geometry",
        "Chapter 8: Linear Programming",
        "Chapter 9: Probability",
        "Applied Math: Financial Mathematics, Linear Programming & Time Series",
        "Full Syllabus / Mixed Chapters"
      ],
      "Informatics Practices (Code 065)": [
        "Unit 1: Data Handling using Pandas and Data Visualization (Matplotlib)",
        "Unit 2: Database Query using SQL (Math, String, Date functions, Group By, Joins)",
        "Unit 3: Introduction to Computer Networks",
        "Unit 4: Societal Impacts (Digital Footprints, Net Etiquette, Cyber Crime, IPR)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Flamingo & Vistas)": [
        "Flamingo Prose: The Last Lesson, Lost Spring, Deep Water, The Rattrap, Indigo, Going Places",
        "Flamingo Poetry: My Mother at Sixty-six, Keeping Quiet, A Thing of Beauty, A Roadside Stand, Aunt Jennifer's Tigers",
        "Vistas: The Third Level, The Tiger King, Journey to the End of the Earth, The Enemy, On the Face of It, Memories of Childhood",
        "Writing Skills: Notice Writing, Invitations, Letters (Job Application/Editor), Articles, Reports",
        "Reading: Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 12 Humanities": {
    subjects: {
      "History (Themes in Indian History I, II, III Rationalized)": [
        "Part I Theme 1: Bricks, Beads and Bones (The Harappan Civilisation)",
        "Part I Theme 2: Kings, Farmers and Towns (Early States and Economies)",
        "Part I Theme 3: Kinship, Caste and Class (Early Societies)",
        "Part I Theme 4: Thinkers, Beliefs and Buildings (Cultural Developments)",
        "Part II Theme 5: Through the Eyes of Travellers",
        "Part II Theme 6: Bhakti-Sufi Traditions",
        "Part II Theme 7: An Imperial Capital: Vijayanagara",
        "Part II Theme 8: Peasants, Zamindars and the State (Agrarian Society & Mughal Empire)",
        "Part III Theme 9: Colonialism and the Countryside (Official Archives)",
        "Part III Theme 10: Rebels and the Raj (1857 Revolt and Representations)",
        "Part III Theme 11: Mahatma Gandhi and the Nationalist Movement",
        "Part III Theme 12: Framing the Constitution (The Beginning of a New Era)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Political Science (Contemporary World & India Since Independence)": [
        "Part A Ch 1: The End of Bipolarity",
        "Part A Ch 2: Contemporary Centres of Power (EU, ASEAN, BRICS)",
        "Part A Ch 3: Contemporary South Asia",
        "Part A Ch 4: International Organisations (UN and its Agencies)",
        "Part A Ch 5: Security in the Contemporary World",
        "Part A Ch 6: Environment and Natural Resources",
        "Part A Ch 7: Globalisation",
        "Part B Ch 1: Challenges of Nation-Building",
        "Part B Ch 2: Era of One-Party Dominance",
        "Part B Ch 3: Politics of Planned Development",
        "Part B Ch 4: India's External Relations",
        "Part B Ch 5: Challenges to and Restoration of the Congress System",
        "Part B Ch 6: The Crisis of Democratic Order (Emergency)",
        "Part B Ch 7: Regional Aspirations",
        "Part B Ch 8: Recent Developments in Indian Politics",
        "Full Syllabus / Mixed Chapters"
      ],
      "Geography (Human Geography & India: People and Economy)": [
        "Fundamentals Ch 1: Human Geography: Nature and Scope",
        "Fundamentals Ch 2: The World Population: Distribution, Density and Growth",
        "Fundamentals Ch 3: Human Development",
        "Fundamentals Ch 4: Primary Activities",
        "Fundamentals Ch 5: Secondary Activities",
        "Fundamentals Ch 6: Tertiary and Quaternary Activities",
        "Fundamentals Ch 7: Transport, Communication and Trade",
        "Fundamentals Ch 8: International Trade",
        "India Ch 1: Population: Distribution, Density, Growth and Composition",
        "India Ch 2: Human Settlements",
        "India Ch 3: Land Resources and Agriculture",
        "India Ch 4: Water Resources",
        "India Ch 5: Mineral and Energy Resources",
        "India Ch 6: Planning and Sustainable Development in Indian Context",
        "India Ch 7: Transport and Communication",
        "India Ch 8: International Trade",
        "India Ch 9: Geographical Perspective on Selected Issues and Problems",
        "Full Syllabus / Mixed Chapters"
      ],
      "Psychology (Psychological Attributes & Applications)": [
        "Chapter 1: Variations in Psychological Attributes",
        "Chapter 2: Self and Personality",
        "Chapter 3: Meeting Life Challenges (Stress and Coping)",
        "Chapter 4: Psychological Disorders",
        "Chapter 5: Therapeutic Approaches",
        "Chapter 6: Attitude and Social Cognition",
        "Chapter 7: Social Influence and Group Processes",
        "Full Syllabus / Mixed Chapters"
      ],
      "Sociology (Indian Society & Social Change in India)": [
        "Book 1 Ch 1: Introducing Indian Society",
        "Book 1 Ch 2: The Demographic Structure of Indian Society",
        "Book 1 Ch 3: Social Institutions: Continuity and Change",
        "Book 1 Ch 4: The Market as a Social Institution",
        "Book 1 Ch 5: Patterns of Social Inequality and Exclusion",
        "Book 1 Ch 6: The Challenges of Cultural Diversity",
        "Book 2 Ch 1: Structural Change",
        "Book 2 Ch 2: Cultural Change",
        "Book 2 Ch 3: Change and Development in Rural Society",
        "Book 2 Ch 4: Change and Development in Industrial Society",
        "Book 2 Ch 5: Social Movements",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics (Macroeconomics & Indian Economic Development)": [
        "Macroeconomics: National Income, Money & Banking",
        "Macroeconomics: Determination of Income & Employment",
        "Macroeconomics: Government Budget & Balance of Payments",
        "Indian Economy: Development Experience (1947–90) & LPG Reforms",
        "Indian Economy: Current Challenges (Human Capital, Rural Development, Employment)",
        "Indian Economy: Sustainable Development & Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core (Flamingo & Vistas)": [
        "Flamingo Prose: The Last Lesson, Lost Spring, Deep Water, The Rattrap, Indigo, Going Places",
        "Flamingo Poetry: My Mother at Sixty-six, Keeping Quiet, A Thing of Beauty, A Roadside Stand, Aunt Jennifer's Tigers",
        "Vistas: The Third Level, The Tiger King, Journey to the End of the Earth, The Enemy, On the Face of It, Memories of Childhood",
        "Writing Skills: Notice Writing, Invitations, Formal Letters, Article / Report Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 11": {
    subjects: {
      "Physics": [
        "Chapter 1: Units and Measurements",
        "Chapter 2: Motion in a Straight Line",
        "Chapter 3: Motion in a Plane",
        "Chapter 4: Laws of Motion",
        "Chapter 5: Work, Energy and Power",
        "Chapter 6: System of Particles and Rotational Motion",
        "Chapter 7: Gravitation",
        "Chapter 8: Mechanical Properties of Solids",
        "Chapter 9: Mechanical Properties of Fluids",
        "Chapter 10: Thermal Properties of Matter",
        "Chapter 11: Thermodynamics",
        "Chapter 12: Kinetic Theory",
        "Chapter 13: Oscillations",
        "Chapter 14: Waves",
        "Full Syllabus / Mixed Chapters"
      ],
      "Chemistry": [
        "Chapter 1: Some Basic Concepts of Chemistry",
        "Chapter 2: Structure of Atom",
        "Chapter 3: Classification of Elements and Periodicity in Properties",
        "Chapter 4: Chemical Bonding and Molecular Structure",
        "Chapter 5: Chemical Thermodynamics",
        "Chapter 6: Equilibrium",
        "Chapter 7: Redox Reactions",
        "Chapter 8: Organic Chemistry: Some Basic Principles and Techniques",
        "Chapter 9: Hydrocarbons",
        "Full Syllabus / Mixed Chapters"
      ],
      "Biology": [
        "Chapter 1: The Living World",
        "Chapter 2: Biological Classification",
        "Chapter 3: Plant Kingdom",
        "Chapter 4: Animal Kingdom",
        "Chapter 5: Morphology of Flowering Plants",
        "Chapter 6: Anatomy of Flowering Plants",
        "Chapter 7: Structural Organisation in Animals",
        "Chapter 8: Cell: The Unit of Life",
        "Chapter 9: Biomolecules",
        "Chapter 10: Cell Cycle and Cell Division",
        "Chapter 11: Photosynthesis in Higher Plants",
        "Chapter 12: Respiration in Plants",
        "Chapter 13: Plant Growth and Development",
        "Chapter 14: Breathing and Exchange of Gases",
        "Chapter 15: Body Fluids and Circulation",
        "Chapter 16: Excretory Products and their Elimination",
        "Chapter 17: Locomotion and Movement",
        "Chapter 18: Neural Control and Coordination",
        "Chapter 19: Chemical Coordination and Integration",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics": [
        "Chapter 1: Sets",
        "Chapter 2: Relations and Functions",
        "Chapter 3: Trigonometric Functions",
        "Chapter 4: Complex Numbers and Quadratic Equations",
        "Chapter 5: Linear Inequalities",
        "Chapter 6: Permutations and Combinations",
        "Chapter 7: Binomial Theorem",
        "Chapter 8: Sequences and Series",
        "Chapter 9: Straight Lines",
        "Chapter 10: Conic Sections",
        "Chapter 11: Introduction to Three Dimensional Geometry",
        "Chapter 12: Limits and Derivatives",
        "Chapter 13: Statistics",
        "Chapter 14: Probability",
        "Full Syllabus / Mixed Chapters"
      ],
      "Accountancy": [
        "Chapter 1: Introduction to Accounting",
        "Chapter 2: Theory Base of Accounting & Accounting Standards",
        "Chapter 3: Recording of Transactions - I (Vouchers, Journal, Ledger)",
        "Chapter 4: Recording of Transactions - II (Cash Book & Other Books)",
        "Chapter 5: Bank Reconciliation Statement (BRS)",
        "Chapter 6: Trial Balance and Rectification of Errors",
        "Chapter 7: Depreciation, Provisions and Reserves",
        "Chapter 8: Financial Statements - I (Without Adjustments)",
        "Chapter 9: Financial Statements - II (With Adjustments)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Business Studies": [
        "Chapter 1: Evolution and Fundamentals of Business",
        "Chapter 2: Forms of Business Organisations",
        "Chapter 3: Public, Private and Global Enterprises",
        "Chapter 4: Business Services (Banking, Insurance, Communication)",
        "Chapter 5: Emerging Modes of Business (e-Business, Outsourcing)",
        "Chapter 6: Social Responsibility of Business and Business Ethics",
        "Chapter 7: Sources of Business Finance",
        "Chapter 8: Small Business and Enterprises",
        "Chapter 9: Internal Trade (Wholesale, Retail, GST Basics)",
        "Chapter 10: International Business",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics": [
        "Statistics Ch 1: Introduction",
        "Statistics Ch 2: Collection of Data",
        "Statistics Ch 3: Organisation of Data",
        "Statistics Ch 4: Presentation of Data (Tables & Graphs)",
        "Statistics Ch 5: Measures of Central Tendency (Mean, Median, Mode)",
        "Statistics Ch 6: Correlation",
        "Statistics Ch 7: Index Numbers",
        "Dev Ch 1: Indian Economy on the Eve of Independence",
        "Dev Ch 2: Indian Economy (1950–1990)",
        "Dev Ch 3: Liberalisation, Privatisation and Globalisation (LPG Reforms)",
        "Dev Ch 4: Human Capital Formation in India",
        "Dev Ch 5: Rural Development",
        "Dev Ch 6: Employment: Growth, Informalisation and Other Issues",
        "Dev Ch 7: Sustainable Economic Development",
        "Dev Ch 8: Development Experiences of India: A Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "History": [
        "Theme 1: Writing and City Life (Mesopotamia)",
        "Theme 2: An Empire Across Three Continents (Roman Empire)",
        "Theme 3: Nomadic Empires (Mongols)",
        "Theme 4: The Three Orders (Western Europe 9th-16th Century)",
        "Theme 5: Changing Cultural Traditions (Renaissance)",
        "Theme 6: Displacing Indigenous Peoples",
        "Theme 7: Paths to Modernisation (Japan and China)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Political Science": [
        "Part A Ch 1: Constitution: Why and How?",
        "Part A Ch 2: Rights in the Indian Constitution",
        "Part A Ch 3: Election and Representation",
        "Part A Ch 4: Executive",
        "Part A Ch 5: Legislature",
        "Part A Ch 6: Judiciary",
        "Part A Ch 7: Federalism",
        "Part A Ch 8: Local Governments",
        "Part B Ch 1: Political Theory: An Introduction",
        "Part B Ch 2: Freedom",
        "Part B Ch 3: Equality",
        "Part B Ch 4: Social Justice",
        "Part B Ch 5: Rights",
        "Part B Ch 6: Citizenship",
        "Part B Ch 7: Nationalism",
        "Part B Ch 8: Secularism",
        "Full Syllabus / Mixed Chapters"
      ],
      "Geography": [
        "Fundamentals Ch 1: Geography as a Discipline",
        "Fundamentals Ch 2: The Origin and Evolution of the Earth",
        "Fundamentals Ch 3: Interior of the Earth",
        "Fundamentals Ch 4: Distribution of Oceans and Continents",
        "Fundamentals Ch 5: Geomorphic Processes",
        "Fundamentals Ch 6: Landforms and their Evolution",
        "Fundamentals Ch 7: Composition and Structure of Atmosphere",
        "Fundamentals Ch 8: Solar Radiation, Heat Balance and Temperature",
        "Fundamentals Ch 9: Atmospheric Circulation and Weather Systems",
        "Fundamentals Ch 10: Water in the Atmosphere",
        "Fundamentals Ch 11: World Climate and Climate Change",
        "Fundamentals Ch 12: Water (Oceans)",
        "Fundamentals Ch 13: Movements of Ocean Water",
        "Fundamentals Ch 14: Biodiversity and Conservation",
        "India Ch 1: India – Location",
        "India Ch 2: Structure and Physiography",
        "India Ch 3: Drainage System",
        "India Ch 4: Climate",
        "India Ch 5: Natural Vegetation",
        "India Ch 6: Soils",
        "India Ch 7: Natural Hazards and Disasters",
        "Full Syllabus / Mixed Chapters"
      ],
      "Psychology": [
        "Chapter 1: What is Psychology?",
        "Chapter 2: Methods of Enquiry in Psychology",
        "Chapter 3: Human Development",
        "Chapter 4: Sensory, Attentional and Perceptual Processes",
        "Chapter 5: Learning",
        "Chapter 6: Human Memory",
        "Chapter 7: Thinking",
        "Chapter 8: Motivation and Emotion",
        "Full Syllabus / Mixed Chapters"
      ],
      "Sociology": [
        "Book 1 Ch 1: Sociology and Society",
        "Book 1 Ch 2: Terms, Concepts and their Use in Sociology",
        "Book 1 Ch 3: Understanding Social Institutions",
        "Book 1 Ch 4: Culture and Socialisation",
        "Book 1 Ch 5: Doing Sociology: Research Methods",
        "Book 2 Ch 1: Social Structure, Stratification and Social Processes",
        "Book 2 Ch 2: Social Change and Social Order in Rural and Urban Society",
        "Book 2 Ch 3: Environment and Society",
        "Book 2 Ch 4: Introducing Western Sociologists",
        "Book 2 Ch 5: Indian Sociologists",
        "Full Syllabus / Mixed Chapters"
      ],
      "Computer Science": [
        "Unit 1: Computer Systems and Organisation",
        "Unit 2: Computational Thinking and Programming - 1 (Python Basics, Conditionals, Loops, Strings, Lists, Tuples, Dictionaries)",
        "Unit 3: Society, Law and Ethics (Cyber Safety, Digital Footprint, Cyber Crime, IT Act)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Informatics Practices": [
        "Unit 1: Introduction to Computer System",
        "Unit 2: Introduction to Python (Basics, Data Types, Control Structures, Lists, Dictionaries)",
        "Unit 3: Database Concepts and Structured Query Language (SQL)",
        "Unit 4: Emerging Trends (AI, IoT, Cloud Computing, Blockchain)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core": [
        "Hornbill: The Portrait of a Lady & A Photograph",
        "Hornbill: We're Not Afraid to Die... If We Can All Be Together",
        "Hornbill: Discovering Tut: the Saga Continues & The Laburnum Top",
        "Hornbill: The Voice of the Rain",
        "Hornbill: Childhood",
        "Hornbill: The Adventure",
        "Hornbill: Silk Road & Father to Son",
        "Snapshots: The Summer of the Beautiful White Horse",
        "Snapshots: The Address",
        "Snapshots: Mother's Day",
        "Snapshots: Birth",
        "Snapshots: The Tale of Melon City",
        "Grammar & Creative Writing: Note Making, Summarizing, Poster Making, Speech, Debate",
        "Reading: Unseen Passages (Comprehension & Note-Making)",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

  "Class 12": {
    subjects: {
      "Physics": [
        "Chapter 1: Electric Charges and Fields",
        "Chapter 2: Electrostatic Potential and Capacitance",
        "Chapter 3: Current Electricity",
        "Chapter 4: Moving Charges and Magnetism",
        "Chapter 5: Magnetism and Matter",
        "Chapter 6: Electromagnetic Induction",
        "Chapter 7: Alternating Current",
        "Chapter 8: Electromagnetic Waves",
        "Chapter 9: Ray Optics and Optical Instruments",
        "Chapter 10: Wave Optics",
        "Chapter 11: Dual Nature of Radiation and Matter",
        "Chapter 12: Atoms",
        "Chapter 13: Nuclei",
        "Chapter 14: Semiconductor Electronics: Materials, Devices and Simple Circuits",
        "Full Syllabus / Mixed Chapters"
      ],
      "Chemistry": [
        "Chapter 1: Solutions",
        "Chapter 2: Electrochemistry",
        "Chapter 3: Chemical Kinetics",
        "Chapter 4: The d- and f-Block Elements",
        "Chapter 5: Coordination Compounds",
        "Chapter 6: Haloalkanes and Haloarenes",
        "Chapter 7: Alcohols, Phenols and Ethers",
        "Chapter 8: Aldehydes, Ketones and Carboxylic Acids",
        "Chapter 9: Amines",
        "Chapter 10: Biomolecules",
        "Full Syllabus / Mixed Chapters"
      ],
      "Biology": [
        "Chapter 1: Sexual Reproduction in Flowering Plants",
        "Chapter 2: Human Reproduction",
        "Chapter 3: Reproductive Health",
        "Chapter 4: Principles of Inheritance and Variation",
        "Chapter 5: Molecular Basis of Inheritance",
        "Chapter 6: Evolution",
        "Chapter 7: Human Health and Disease",
        "Chapter 8: Microbes in Human Welfare",
        "Chapter 9: Biotechnology: Principles and Processes",
        "Chapter 10: Biotechnology and its Applications",
        "Chapter 11: Organisms and Populations",
        "Chapter 12: Ecosystem",
        "Chapter 13: Biodiversity and Conservation",
        "Full Syllabus / Mixed Chapters"
      ],
      "Mathematics": [
        "Chapter 1: Relations and Functions",
        "Chapter 2: Inverse Trigonometric Functions",
        "Chapter 3: Matrices",
        "Chapter 4: Determinants",
        "Chapter 5: Continuity and Differentiability",
        "Chapter 6: Application of Derivatives",
        "Chapter 7: Integrals",
        "Chapter 8: Application of Integrals",
        "Chapter 9: Differential Equations",
        "Chapter 10: Vector Algebra",
        "Chapter 11: Three Dimensional Geometry",
        "Chapter 12: Linear Programming",
        "Chapter 13: Probability",
        "Full Syllabus / Mixed Chapters"
      ],
      "Accountancy": [
        "Part A Ch 1: Accounting for Partnership: Basic Concepts",
        "Part A Ch 2: Goodwill: Nature and Valuation",
        "Part A Ch 3: Change in Profit-Sharing Ratio Among Existing Partners",
        "Part A Ch 4: Admission of a Partner",
        "Part A Ch 5: Retirement and Death of a Partner",
        "Part A Ch 6: Dissolution of a Partnership Firm",
        "Part B Ch 1: Accounting for Share Capital (Issue, Forfeiture, Reissue)",
        "Part B Ch 2: Issue and Redemption of Debentures",
        "Part B Ch 3: Financial Statements of a Company",
        "Part B Ch 4: Analysis of Financial Statements (Comparative & Common Size)",
        "Part B Ch 5: Accounting Ratios (Liquidity, Solvency, Activity, Profitability)",
        "Part B Ch 6: Cash Flow Statement (AS-3 Revised)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Business Studies": [
        "Part I Ch 1: Nature and Significance of Management",
        "Part I Ch 2: Principles of Management (Fayol & Taylor)",
        "Part I Ch 3: Business Environment",
        "Part I Ch 4: Planning",
        "Part I Ch 5: Organising",
        "Part I Ch 6: Staffing",
        "Part I Ch 7: Directing",
        "Part I Ch 8: Controlling",
        "Part II Ch 9: Financial Management",
        "Part II Ch 10: Financial Markets (Money & Capital Market)",
        "Part II Ch 11: Marketing Management",
        "Part II Ch 12: Consumer Protection (CPA 2019)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Economics": [
        "Macro Ch 1: Introduction to Macroeconomics",
        "Macro Ch 2: National Income Accounting and Related Aggregates",
        "Macro Ch 3: Money and Banking (Commercial & Central Bank)",
        "Macro Ch 4: Determination of Income and Employment (AD-AS, Multiplier)",
        "Macro Ch 5: Government Budget and the Economy",
        "Macro Ch 6: Balance of Payments and Foreign Exchange Rate",
        "Dev Ch 1: Development Experience (1947–90) and Economic Reforms since 1991",
        "Dev Ch 2: Current Challenges Facing Indian Economy (Human Capital, Rural Development)",
        "Dev Ch 3: Employment, Infrastructure and Sustainable Development",
        "Dev Ch 4: Development Experience of India: A Comparison with Neighbours",
        "Full Syllabus / Mixed Chapters"
      ],
      "History": [
        "Part I Theme 1: Bricks, Beads and Bones (The Harappan Civilisation)",
        "Part I Theme 2: Kings, Farmers and Towns (Early States and Economies)",
        "Part I Theme 3: Kinship, Caste and Class (Early Societies)",
        "Part I Theme 4: Thinkers, Beliefs and Buildings (Cultural Developments)",
        "Part II Theme 5: Through the Eyes of Travellers",
        "Part II Theme 6: Bhakti-Sufi Traditions",
        "Part II Theme 7: An Imperial Capital: Vijayanagara",
        "Part II Theme 8: Peasants, Zamindars and the State (Agrarian Society & Mughal Empire)",
        "Part III Theme 9: Colonialism and the Countryside (Official Archives)",
        "Part III Theme 10: Rebels and the Raj (1857 Revolt and Representations)",
        "Part III Theme 11: Mahatma Gandhi and the Nationalist Movement",
        "Part III Theme 12: Framing the Constitution (The Beginning of a New Era)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Political Science": [
        "Part A Ch 1: The End of Bipolarity",
        "Part A Ch 2: Contemporary Centres of Power (EU, ASEAN, BRICS)",
        "Part A Ch 3: Contemporary South Asia",
        "Part A Ch 4: International Organisations (UN and its Agencies)",
        "Part A Ch 5: Security in the Contemporary World",
        "Part A Ch 6: Environment and Natural Resources",
        "Part A Ch 7: Globalisation",
        "Part B Ch 1: Challenges of Nation-Building",
        "Part B Ch 2: Era of One-Party Dominance",
        "Part B Ch 3: Politics of Planned Development",
        "Part B Ch 4: India's External Relations",
        "Part B Ch 5: Challenges to and Restoration of the Congress System",
        "Part B Ch 6: The Crisis of Democratic Order (Emergency)",
        "Part B Ch 7: Regional Aspirations",
        "Part B Ch 8: Recent Developments in Indian Politics",
        "Full Syllabus / Mixed Chapters"
      ],
      "Geography": [
        "Fundamentals Ch 1: Human Geography: Nature and Scope",
        "Fundamentals Ch 2: The World Population: Distribution, Density and Growth",
        "Fundamentals Ch 3: Human Development",
        "Fundamentals Ch 4: Primary Activities",
        "Fundamentals Ch 5: Secondary Activities",
        "Fundamentals Ch 6: Tertiary and Quaternary Activities",
        "Fundamentals Ch 7: Transport, Communication and Trade",
        "Fundamentals Ch 8: International Trade",
        "India Ch 1: Population: Distribution, Density, Growth and Composition",
        "India Ch 2: Human Settlements",
        "India Ch 3: Land Resources and Agriculture",
        "India Ch 4: Water Resources",
        "India Ch 5: Mineral and Energy Resources",
        "India Ch 6: Planning and Sustainable Development in Indian Context",
        "India Ch 7: Transport and Communication",
        "India Ch 8: International Trade",
        "India Ch 9: Geographical Perspective on Selected Issues and Problems",
        "Full Syllabus / Mixed Chapters"
      ],
      "Psychology": [
        "Chapter 1: Variations in Psychological Attributes",
        "Chapter 2: Self and Personality",
        "Chapter 3: Meeting Life Challenges (Stress and Coping)",
        "Chapter 4: Psychological Disorders",
        "Chapter 5: Therapeutic Approaches",
        "Chapter 6: Attitude and Social Cognition",
        "Chapter 7: Social Influence and Group Processes",
        "Full Syllabus / Mixed Chapters"
      ],
      "Sociology": [
        "Book 1 Ch 1: Introducing Indian Society",
        "Book 1 Ch 2: The Demographic Structure of Indian Society",
        "Book 1 Ch 3: Social Institutions: Continuity and Change",
        "Book 1 Ch 4: The Market as a Social Institution",
        "Book 1 Ch 5: Patterns of Social Inequality and Exclusion",
        "Book 1 Ch 6: The Challenges of Cultural Diversity",
        "Book 2 Ch 1: Structural Change",
        "Book 2 Ch 2: Cultural Change",
        "Book 2 Ch 3: Change and Development in Rural Society",
        "Book 2 Ch 4: Change and Development in Industrial Society",
        "Book 2 Ch 5: Social Movements",
        "Full Syllabus / Mixed Chapters"
      ],
      "Computer Science": [
        "Unit 1: Computational Thinking and Programming - 2 (Python Revision, Functions, File Handling: Text, Binary, CSV)",
        "Unit 1: Data Structure: Stack using Python List",
        "Unit 2: Computer Networks (Evolution, Topologies, Protocols, Network Security)",
        "Unit 3: Database Management (SQL Queries, Aggregate Functions, Joins, Python-SQL Interface)",
        "Full Syllabus / Mixed Chapters"
      ],
      "Informatics Practices": [
        "Unit 1: Data Handling using Pandas and Data Visualization (Matplotlib)",
        "Unit 2: Database Query using SQL (Math, String, Date functions, Group By, Joins)",
        "Unit 3: Introduction to Computer Networks",
        "Unit 4: Societal Impacts (Digital Footprints, Net Etiquette, Cyber Crime, IPR)",
        "Full Syllabus / Mixed Chapters"
      ],
      "English Core": [
        "Flamingo Prose: The Last Lesson (Alphonse Daudet)",
        "Flamingo Prose: Lost Spring (Anees Jung)",
        "Flamingo Prose: Deep Water (William Douglas)",
        "Flamingo Prose: The Rattrap (Selma Lagerlöf)",
        "Flamingo Prose: Indigo (Louis Fischer)",
        "Flamingo Prose: Poets and Pancakes (Asokamitran)",
        "Flamingo Prose: The Interview (Christopher Silvester)",
        "Flamingo Prose: Going Places (A. R. Barton)",
        "Flamingo Poetry: My Mother at Sixty-six (Kamala Das)",
        "Flamingo Poetry: Keeping Quiet (Pablo Neruda)",
        "Flamingo Poetry: A Thing of Beauty (John Keats)",
        "Flamingo Poetry: A Roadside Stand (Robert Frost)",
        "Flamingo Poetry: Aunt Jennifer's Tigers (Adrienne Rich)",
        "Vistas: The Third Level (Jack Finney)",
        "Vistas: The Tiger King (Kalki)",
        "Vistas: Journey to the End of the Earth (Tishani Doshi)",
        "Vistas: The Enemy (Pearl S. Buck)",
        "Vistas: On the Face of It (Susan Hill)",
        "Vistas: Memories of Childhood (Zitkala-Sa & Bama)",
        "Writing Skills: Notice Writing, Invitations and Replies, Formal Letter (Job Application / Editor), Article / Report Writing",
        "Reading: Reading Comprehension Passages",
        "Full Syllabus / Mixed Chapters"
      ],
    }
  },

};
